- src/contexts/AzureMapDataSourceContext.tsx
- src/contexts/AzureMapLayerContext.tsx
- src/types.ts
1. Datasource onUnmount fix
2. Added events on layer
3. Added events on DataSource
> fix: datasource return fix, add events to layers on click

- docs/assets/js/search.js
- docs/classes/azuremapsstatefulprovider.html
- docs/globals.html
- docs/index.html
- src/components/AzureMap/AzureMap.tsx
- src/components/AzureMap/useCreateMapControls.tsx
- src/components/AzureMapMarkers/AzureMapHtmlMarker/AzureMapHtmlMarker.tsx
- src/types.ts
> feat: add custom controls property

- src/hooks/useAzureMapLayer.ts
- src/types.ts
> feat: bubble layer

- src/components/AzureMapPopup/AzureMapPopup.tsx
- src/components/AzureMapPopup/useCreateAzureMapPopup.ts
Resolves https://github.com/WiredSolutions/react-azure-maps/issues/36
> fix: handle options change for popup

- src/components/AzureMapMarkers/AzureMapHtmlMarker/AzureMapHtmlMarker.tsx
Resolves https://github.com/WiredSolutions/react-azure-maps/issues/38
> fix: HtmlMarker content props change

- src/components/AzureMap/useCreateSprites.tsx
- src/types.ts
Custom image sprite to in Polygon or Symbol layer as Feature
> feat: custom image sprite

- package.json
- src/contexts/AzureMapDataSourceContext.tsx
- src/types.ts
- yarn.lock
- Added `add` function 
- Datasource options useEffect
- Reverted azure-maps-control version for adjust to spatial-io
> feat: datasource touch-ups, adjust to spatial-io

- __mocks__/azure-maps-control.js
- src/components/AzureMap/AzureMap.test.tsx
- src/components/AzureMap/useCreateSprites.test.tsx
- src/contexts/AzureMapContext.test.tsx
- src/contexts/AzureMapDataSourceContext.test.tsx
- src/contexts/AzureMapLayerContext.test.tsx
- src/contexts/__snapshots__/AzureMapLayerContext.test.tsx.snap
- src/hooks/constructLayer.test.tsx
- src/hooks/useAzureMapLayer.test.tsx
- src/hooks/useCheckRef.test.tsx
> Add missing test cases for components

- __mocks__/azure-maps-control.js
- src/components/AzureMapFeature/useCreateAzureMapFeature.test.tsx
- src/components/AzureMapFeature/useFeature.test.tsx
- src/components/AzureMapMarkers/AzureMapHtmlMarker/AzureMapHtmlMarker.test.tsx
- src/components/AzureMapMarkers/AzureMapHtmlMarker/__snapshots__/AzureMapHtmlMarker.test.tsx.snap
- src/components/AzureMapPopup/AzureMapPopup.test.tsx
- src/components/helpers/mapHelper.test.ts
> Add html marker tests

- src/components/AzureMap/AzureMap.test.tsx
- src/components/AzureMap/AzureMap.tsx
> fix: initial options

- __mocks__/azure-maps-control.js
- src/components/AzureMap/AzureMap.test.tsx
- src/components/AzureMap/AzureMap.tsx
- src/types.ts
Added props and effect for style and service options.
Now it able to change style and service options dynamically.
> feat: add props and effect for StyleOptions and ServiceOptions

- package.json
- yarn.lock
update azure-maps-control lib to newest version - 2.0.31
> feat: update azure-maps-control lib to newest version - 2.0.31

- src/contexts/AzureMapContext.tsx
- src/react-azure-maps.ts
Created Azure Maps Context Hook
> feat: create Azure Maps Context Hook

- src/types.ts
Fix for: https://github.com/WiredSolutions/react-azure-maps/issues/72
> fix: update type of IAzureDataSourceChildren

- package.json
Fix peer dependency version of react 17
> feat(deps): bump peer dependency versions

- package.json
> fix package json incorrect imports

- package.json
- https://github.com/Azure/react-azure-maps/pull/147
- https://github.com/Azure/react-azure-maps/pull/133
> chore: bump version to 0.4.5

- package.json
- preview/react-preview.jsx
- https://github.com/Azure/react-azure-maps/pull/150
> chore: bump version to 0.4.6

- __mocks__/azure-maps-control.js
- package.json
- src/components/AzureMapMarkers/AzureMapHtmlMarker/AzureMapHtmlMarker.test.tsx
- src/components/AzureMapMarkers/AzureMapHtmlMarker/AzureMapHtmlMarker.tsx
- Simplified logic to toggle the popup with `isPopupVisible` in `AzureMapHtmlMarker`
- Fixes https://github.com/Azure/react-azure-maps/issues/152
> fix: isPopupVisible logic for AzureMapHtmlMarker

- README.md
Add documentation for other authentication options.
> chore: add authentication options in README

- src/components/AzureMap/AzureMap.tsx
Fix unit test failures caused by commit https://github.com/Azure/react-azure-maps/commit/6de3e9c900a123009a7662321e8123867629bcf9
> fix: unit test failures

- .github/workflows/nodejs.yml
- .github/workflows/npm-release.yml
- package-lock.json
- package.json
Upgraded to support React 19 and tested with playground project.
> feat: support react 19

- .github/workflows/npm-release.yml
- package.json
Bump version to 1.0.3:
- Resolved issue #87
> chore: release v1.0.3
